### get welcome
GET http://localhost:3000/
### get admin with id
GET http://localhost:3000/admin/123545
### post admin
POST http://localhost:3000/admin
Content-Type: application/json

{
    "login":"rodrigo",
    "password":"12345"
}
### set cookie
GET http://localhost:3000/setcookie
### get cookie
GET http://localhost:3000/getcookie